### ISSUE TITLE
删除文件错误

### ISSUE THREAD

**Issue by ghost** [GoAdminGroup/filemanager#5]
![屏幕截图 2021-03-05 153507](https://user-images.githubusercontent.com/20684744/110082577-7d0f0680-7dc8-11eb-82af-ce5d8ace1ed1.png)

右侧删除按钮，删除时：
```
http://127.0.0.1:8199/admin/fm/def/deleteundefined
```
查看代码：
```

$('.grid-row-delete').click(function () {
--
DeletePost($(this).data('id'), $(this).data('param'))});
  




function DeletePost(id, url_param) {
--
  | swal({
  | title: "你确定要删除吗？",
  | type: "warning",
  | showCancelButton: true,
  | confirmButtonColor: "#DD6B55",
  | confirmButtonText: "确定",
  | closeOnConfirm: false,
  | cancelButtonText: "取消",
  | },
  | function () {
  | $.ajax({
  | method: 'post',
  | url: "/admin/fm/def/delete" + url_param,
  | data: {
  | id: id
  | },


```
应该是 url_param 没有正确抓取到 参数 url_param

**Comment by ghost** [comment]
正常删除按钮：
```
<a href="javascript:void(0);" data-id="4" data-param="" class="grid-row-delete">
```
filemanager 按钮
```
<a class="grid-row-delete" data-id="/a.jpg" data-title="" href="">删除</a>
```
缺少了 ，data-param=""

可惜，往下就不知道怎么修改了 😂

**Comment by junyongNie** [comment]
我也遇到了这个问题，不知道作者有时间修复嘛

**Comment by junyongNie** [comment]
> 正常删除按钮：
> 
> ```
> <a href="javascript:void(0);" data-id="4" data-param="" class="grid-row-delete">
> ```
> 
> filemanager 按钮
> 
> ```
> <a class="grid-row-delete" data-id="/a.jpg" data-title="" href="">删除</a>
> ```
> 
> 缺少了 ，data-param=""
> 
> 可惜，往下就不知道怎么修改了 😂


GO111MODULE=on GOPROXY=https://goproxy.io go get github.com/GoAdminGroup/themes@pre-release

> ![屏幕截图 2021-03-05 153507](https://user-images.githubusercontent.com/20684744/110082577-7d0f0680-7dc8-11eb-82af-ce5d8ace1ed1.png)
> 
> 右侧删除按钮，删除时：
> 
> ```
> http://127.0.0.1:8199/admin/fm/def/deleteundefined
> ```
> 
> 查看代码：
> 
> ```
> 
> $('.grid-row-delete').click(function () {
> --
> DeletePost($(this).data('id'), $(this).data('param'))});
>   
> 
> 
> 
> 
> function DeletePost(id, url_param) {
> --
>   | swal({
>   | title: "你确定要删除吗？",
>   | type: "warning",
>   | showCancelButton: true,
>   | confirmButtonColor: "#DD6B55",
>   | confirmButtonText: "确定",
>   | closeOnConfirm: false,
>   | cancelButtonText: "取消",
>   | },
>   | function () {
>   | $.ajax({
>   | method: 'post',
>   | url: "/admin/fm/def/delete" + url_param,
>   | data: {
>   | id: id
>   | },
> ```
> 
> 应该是 url_param 没有正确抓取到 参数 url_param

修复已经提到预发布分支。你可以拉下来试下。在项目根目录执行上面命令就可以。
GO111MODULE=on GOPROXY=https://goproxy.io go get github.com/GoAdminGroup/themes@pre-release

**Comment by junyongNie** [comment]
> ![屏幕截图 2021-03-05 153507](https://user-images.githubusercontent.com/20684744/110082577-7d0f0680-7dc8-11eb-82af-ce5d8ace1ed1.png)
> 
> 右侧删除按钮，删除时：
> 
> ```
> http://127.0.0.1:8199/admin/fm/def/deleteundefined
> ```
> 
> 查看代码：
> 
> ```
> 
> $('.grid-row-delete').click(function () {
> --
> DeletePost($(this).data('id'), $(this).data('param'))});
>   
> 
> 
> 
> 
> function DeletePost(id, url_param) {
> --
>   | swal({
>   | title: "你确定要删除吗？",
>   | type: "warning",
>   | showCancelButton: true,
>   | confirmButtonColor: "#DD6B55",
>   | confirmButtonText: "确定",
>   | closeOnConfirm: false,
>   | cancelButtonText: "取消",
>   | },
>   | function () {
>   | $.ajax({
>   | method: 'post',
>   | url: "/admin/fm/def/delete" + url_param,
>   | data: {
>   | id: id
>   | },
> ```
> 
> 应该是 url_param 没有正确抓取到 参数 url_param

修复已经提到预发布分支。你可以拉下来试下。在项目根目录执行上面命令就可以。
GO111MODULE=on GOPROXY=https://goproxy.io go get github.com/GoAdminGroup/themes@pre-release

**Comment by ghost** [comment]
可以，谢谢
